# Generated by Django 4.1.7 on 2023-05-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listings_seller"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Listings",
            new_name="Listing",
        ),
    ]
