# Generated by Django 4.1.7 on 2023-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_category_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
