# Generated by Django 4.1.7 on 2023-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_status_alter_listing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created_on",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
