# Generated by Django 4.1.7 on 2023-05-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_bid_alter_listing_start_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="listing",
            name="start_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_price",
                to="auctions.bid",
            ),
        ),
    ]
